<select name="nationality" class="form-control" title="الجنسية" title="اختر الدولة"autofocus required>
	<option value="" selected disabled>اختر الدولة..</option>
                                <option value="533">ARUBA - أروبا                 </option>
                                <option value="230">ETHIOPIA - اثيوبيا               </option>
                                <option value="31">AZERBAIJAN - اذريبيجان             </option>
                                <option value="51">ARMENIA - ارمينيا               </option>
                                <option value="80">ERITREA - اريتريا               </option>
                                <option value="724">SPAIN - اسبانيا               </option>
                                <option value="36">AUSTRALIA - استراليا              </option>
                                <option value="233">ESTINIA - استونيا               </option>
                                <option value="140">CENTRAL AFRICAN - افريقيا الوسطي        </option>
                                <option value="4">AFGHANISTAN - افغانستان             </option>
                                <option value="32">ARGENTINA - الارجنتين             </option>
                                <option value="400">JORDAN - الاردن                </option>
                                <option value="218">ECUADOR - الاكوادور             </option>
                                <option value="784">U.A.E. - الامارات              </option>
                                <option value="888">U.N. - الامم المتحدة         </option>
                                <option value="532">NETHERLANDS ANTILLES - الانتيل الهولندية     </option>
                                <option value="858">URUGUAY - الاوروجواي            </option>
                                <option value="8">ALBANIA - البانيا               </option>
                                <option value="48">BAHRAIN - البحرين               </option>
                                <option value="76">BRAZIL - البرازيل              </option>
                                <option value="620">PORTUGAL - البرتغال              </option>
                                <option value="544">BOSNIA &amp; HERZEGOVINA - البوسنة والهرسك       </option>
                                <option value="499">MONTENEGRO - الجبل الأسود          </option>
                                <option value="12">ALGERIA - الجزائر               </option>
                                <option value="208">DENMARK - الدنمارك              </option>
                                <option value="222">EL SALVADOR - السالفادور            </option>
                                <option value="682">SAUDI ARABIA - السعودية              </option>
                                <option value="686">SENEGAL - السنغال               </option>
                                <option value="736">SUDAN - السودان               </option>
                                <option value="752">SWEDEN - السويد                </option>
                                <option value="732">SAHARA W - الصحراء الغربية       </option>
                                <option value="706">SOMALIA - الصومال               </option>
                                <option value="368">IRAQ - العراق                </option>
                                <option value="266">GABON - الغابون               </option>
                                <option value="336">VATICAN - الفاتيكان             </option>
                                <option value="608">PHILIPPINES - الفلبين               </option>
                                <option value="120">CAMEROON - الكاميرون             </option>
                                <option value="178">CONGO - الكونجو               </option>
                                <option value="180">DEMOCRATIC CONGO - الكونجو الديمقراطية   </option>
                                <option value="414">KUWAIT - الكويت                </option>
                                <option value="280">GERMANY - المانيا               </option>
                                <option value="348">HUNGARY - المجر                 </option>
                                <option value="504">MOROCCO - المغرب                </option>
                                <option value="484">MEXICO - المكسيك               </option>
                                <option value="40">AUSTRIA - النمسا                </option>
                                <option value="578">NORWAY - النورويج              </option>
                                <option value="562">NIGER - النيجر                </option>
                                <option value="356">INDIA - الهند                 </option>
                                <option value="840">U.S.A. - الولايات المتحدة      </option>
                                <option value="392">JAPAN - اليابان               </option>
                                <option value="886">YEMEN - اليمن                 </option>
                                <option value="300">GREECE - اليونان               </option>
                                <option value="28">ANTIGUA AND BARBUDA - انتيجوا و باربودا     </option>
                                <option value="24">ANGOLA - انجولا                </option>
                                <option value="20">ANDORRA - اندورا                </option>
                                <option value="360">INDONESIA - اندونيسيا             </option>
                                <option value="860">UZBEKISTAN - اوزبكستان             </option>
                                <option value="800">UGANDA - اوغندا                </option>
                                <option value="804">UKRAINE - اوكرانيا              </option>
                                <option value="364">IRAN - ايران                 </option>
                                <option value="372">IRELAND - ايرلندا               </option>
                                <option value="352">ICELAND - ايسلاندا              </option>
                                <option value="380">ITALY - ايطاليا               </option>
                                <option value="598">PAPUA NG - بابوا نيو غينيا       </option>
                                <option value="600">PARAGUAY - باراجواي              </option>
                                <option value="52">BARBADOS - باربادوس              </option>
                                <option value="586">PAKISTAN - باكستان               </option>
                                <option value="60">BERMUDA - برمودا                </option>
                                <option value="96">BRUNEI DARUSSALAM - بروناي دار السلام     </option>
                                <option value="108">BURUNDI - بروندي                </option>
                                <option value="826">U K - بريطانيا              </option>
                                <option value="56">BELGIUM - بلجيكا                </option>
                                <option value="100">BULGARIA - بلغاريا               </option>
                                <option value="50">BANGLADESH - بنغلاديش              </option>
                                <option value="590">PANAMA - بنما                  </option>
                                <option value="44">BAHAMAS - بهاماس                </option>
                                <option value="64">BHUTAN - بوتان                 </option>
                                <option value="72">BOTSWANA - بوتسوانا              </option>
                                <option value="630">PUERTO RICO - بورتوريكو             </option>
                                <option value="854">BURKINA FASO - بوركينافاسو           </option>
                                <option value="585">PALAU - بولا                  </option>
                                <option value="616">POLAND - بولندا                </option>
                                <option value="258">FRENCH POLYNESIA - بولنيسياالفرنسية      </option>
                                <option value="68">BOLIVIA - بوليفيا               </option>
                                <option value="612">PITCAIRN - بيتكيرن               </option>
                                <option value="604">PERU - بيرو                  </option>
                                <option value="112">BELARUS - بيلروس                </option>
                                <option value="84">BELIZE - بيليز                 </option>
                                <option value="204">BENIN - بينين                 </option>
                                <option value="764">THAILAND - تايلاند               </option>
                                <option value="795">TURKMENIST - تركمانستان            </option>
                                <option value="792">TURKEY - تركيا                 </option>
                                <option value="780">TRINIDAD AND TOBAGO - ترينادا وتوباجو       </option>
                                <option value="148">CHAD - تشاد                  </option>
                                <option value="200">CZECHO - تشيك                  </option>
                                <option value="152">CHILE - تشيلي                 </option>
                                <option value="834">TANZANIA - تنزانيا               </option>
                                <option value="768">TOGO - توغو                  </option>
                                <option value="798">TUVALU - توفالو                </option>
                                <option value="776">TONGA - تونجا                 </option>
                                <option value="788">TUNISIA - تونس                  </option>
                                <option value="626">TIMOR ES - تيمور الشرقية         </option>
                                <option value="901">R.O.C.TAIWAN - ج. الصين (تايوان)     </option>
                                <option value="156">CHINA - ج.الصين الشعبية       </option>
                                <option value="292">GIBRLTAR - جبل طارق              </option>
                                <option value="308">GRENADA - جرينادا               </option>
                                <option value="304">GREENLAND - جرينلند               </option>
                                <option value="830">CHANNEL IALSND - جزر القنال الانجليزي  </option>
                                <option value="462">MALDIVES - جزر المالديف          </option>
                                <option value="86">BRITISH INDIAN OCEAN - جزر المحيط الهندي     </option>
                                <option value="584">MARSHALL ISLANDS - جزر المرشال           </option>
                                <option value="582">PACFC IL - جزر الهادي            </option>
                                <option value="74">BOUVET ISLAND - جزر بوفت              </option>
                                <option value="396">JOHNSTON - جزر جونستون           </option>
                                <option value="334">HEARD AND MC DONALD - جزر دونالد            </option>
                                <option value="90">SOLOMON ISLANDS - جزر سليمان            </option>
                                <option value="238">FALKLAND ISLANDS - جزر فوكلند            </option>
                                <option value="850">VG IS US - جزر فيرجن             </option>
                                <option value="162">CHRISIMAS ISLAND - جزر كرسمس             </option>
                                <option value="184">COOK ISLAND - جزر كوك               </option>
                                <option value="166">COCOS KEELING ISLAND - جزر كوكوس             </option>
                                <option value="136">CAYMEN ISLANDS - جزر كيمان             </option>
                                <option value="488">MIDWAY - جزر مدوي              </option>
                                <option value="580">NORTHERN MARIANA ISL - جزر مريانا            </option>
                                <option value="876">WALS &amp; FT - جزر والس وفوتونا      </option>
                                <option value="796">TKS &amp; CA - جزرالترك وكايكو       </option>
                                <option value="660">ANGUILLA - جزيرة أنجويلا         </option>
                                <option value="248">ALAND ISLANDS - جزيرة أولند           </option>
                                <option value="832">JERSEY - جزيرة جيرزي           </option>
                                <option value="831">GUERNESEY - جزيرة جيزنزي          </option>
                                <option value="833">ISLE OF MAN - جزيرة مان             </option>
                                <option value="175">MAYOTTE - جزيرة مايوت           </option>
                                <option value="574">NORFOLK ISLAND - جزيرة نورفوك          </option>
                                <option value="872">WAKE ISL - جزيرة ويك             </option>
                                <option value="388">JAMAICA - جمايكا                </option>
                                <option value="174">COMOROS - جمهورية القمرالمتحدة  </option>
                                <option value="214">DOMINICAN REPUBLIC - جمهورية دومنيكان      </option>
                                <option value="991">REPUBLIC OF KOSOVO - جمهورية كوسوفو        </option>
                                <option value="132">CAPE VERDE - جمهوريةالرأس الاخضر   </option>
                                <option value="710">SOUTH AFRICA - جنوب افريقيا          </option>
                                <option value="728">SOUTH SUDAN - جنوب السودان          </option>
                                <option value="320">GUATEMALA - جواتيمالا             </option>
                                <option value="983">GUADER - جوادر                 </option>
                                <option value="312">GUADELOUPE - جواديلوب              </option>
                                <option value="268">GEORGIA - جورجيا                </option>
                                <option value="262">DJIBOUTI - جيبوتي                </option>
                                <option value="212">DOMINICA - دومينيكا              </option>
                                <option value="646">RWANDA - رواندا                </option>
                                <option value="643">RUSSIA - روسيا                 </option>
                                <option value="642">ROMANIA - رومانيا               </option>
                                <option value="638">REUNION - ريونيون               </option>
                                <option value="894">ZAMBIA - زامبيا                </option>
                                <option value="716">ZIMBABWE - زمبوابوي              </option>
                                <option value="678">SAO T&amp;P - سافوتوم و برنسيت      </option>
                                <option value="663">SAIT-MARTIN - سالت مارتن            </option>
                                <option value="882">SAMOA - ساموا                 </option>
                                <option value="16">AMIRICAN SAMOA - ساموا الامريكية       </option>
                                <option value="652">SAINT BARTHELEMY - سان بارتليمي          </option>
                                <option value="674">SAN MARINO - سان مارينو            </option>
                                <option value="659">SAINT KITTS &amp; NEVIS - سانت كيتس ونيفيس      </option>
                                <option value="981">ZANIBAR - سانسيبار              </option>
                                <option value="144">SRI LANK - سريلانكا              </option>
                                <option value="744">SVALBARD AND JAN - سفالبارد وجان ماين    </option>
                                <option value="703">SLOVAKIA - سلوفكيا               </option>
                                <option value="705">SLOVENIA - سلوفنيا               </option>
                                <option value="666">ST PIR&amp;MQ - سنت بير وميكليون      </option>
                                <option value="670">ST VINCT&amp;GRDN - سنت فينسنت            </option>
                                <option value="658">ST CHRIS - سنت كريستوفر          </option>
                                <option value="662">SAINT LUCIA - سنت لوسيا             </option>
                                <option value="654">SAINT HELENA - سنت هيلانا            </option>
                                <option value="702">SINGAPORE - سنغافورة              </option>
                                <option value="748">SWAZILAND - سوازيلاند             </option>
                                <option value="760">SYRIA - سوريا                 </option>
                                <option value="740">SURINAME - سورينام               </option>
                                <option value="756">SWITZERLAND - سويسرا                </option>
                                <option value="694">SIERRA LEONE - سيراليون              </option>
                                <option value="690">SEYCHELLES - سيشيل                 </option>
                                <option value="688">SERBIA - صربيا                 </option>
                                <option value="891">SERBIA &amp;MONTENEGRO - صربيا و الجبل الاسود  </option>
                                <option value="762">TAJIKISTAN - طاجكستان              </option>
                                <option value="772">TOKELAU - طوكيلاو               </option>
                                <option value="512">OMAN - عمان                  </option>
                                <option value="270">GAMBIA - غامبيا                </option>
                                <option value="288">GHANA - غانا                  </option>
                                <option value="316">GUAM - غوامي                 </option>
                                <option value="254">FRENCH GUIANA - غيانا الفرنسية        </option>
                                <option value="328">GUYANA - غيانيا                </option>
                                <option value="324">GUINEA - غينيا                 </option>
                                <option value="226">EQUATORIAL GUINEA - غينيا الاستوائية      </option>
                                <option value="624">GUINEA-BISSAU - غينيا بيساو           </option>
                                <option value="234">FAEROE ISLANDS - فارو                  </option>
                                <option value="548">VANUATU - فانواتو               </option>
                                <option value="92">BRITISH VIRGIN ISLND - فرجين البريطانية      </option>
                                <option value="250">FRANCE - فرنسا                 </option>
                                <option value="999">PALESTIN - فلسطين                </option>
                                <option value="246">FINLAND - فنلندا                </option>
                                <option value="862">VENEZUELA - فنيزويلا              </option>
                                <option value="704">VIETNAM - فيتنام                </option>
                                <option value="242">FIJI - فيجي                  </option>
                                <option value="196">CYPRUS - قبرص                  </option>
                                <option value="634">QATAR - قطر                   </option>
                                <option value="191">CROATIA - كرواتيا               </option>
                                <option value="296">KIRIBATI - كريباتي               </option>
                                <option value="398">KAZAKHSTAN - كزخستان               </option>
                                <option value="116">CAMBODIA - كمبوديا               </option>
                                <option value="124">CANADA - كندا                  </option>
                                <option value="192">CUBA - كوبا                  </option>
                                <option value="384">COTE DIVOIRE - كوت ديفوار            </option>
                                <option value="410">KOREA ST - كوريا الجنوبية        </option>
                                <option value="408">NORTH KOREA - كوريا الشمالية        </option>
                                <option value="188">COSTA RICA - كوستاريكا             </option>
                                <option value="170">COLOMBIA - كولومبيا              </option>
                                <option value="417">KYRGYZSTAN - كيرغيستان             </option>
                                <option value="404">KENYA - كينيا                 </option>
                                <option value="428">LATVIA - لاتفيا                </option>
                                <option value="418">LAO - لاو                   </option>
                                <option value="422">LEBANON - لبنان                 </option>
                                <option value="440">LITHUANIA - لتوانيا               </option>
                                <option value="442">LUXEMBOURG - لكسمبورج              </option>
                                <option value="434">LIBYA - ليبيا                 </option>
                                <option value="430">LIBERIA - ليبيريا               </option>
                                <option value="426">LESOTHO - ليسوتو                </option>
                                <option value="438">LIECHTENSTEIN - ليشتنشين              </option>
                                <option value="474">MARTINIQUE - مارتنيك               </option>
                                <option value="446">MACAO - ماكاو                 </option>
                                <option value="454">MALAWI - مالاوي                </option>
                                <option value="470">MALTA - مالطا                 </option>
                                <option value="466">MALI - مالي                  </option>
                                <option value="458">MALAYSIA - ماليزيا               </option>
                                <option value="450">MADAGASCAR - مداغاسكر              </option>
                                <option value="818">EGYPT - مصر                   </option>
                                <option value="807">MACEDONIA - مقدونيا               </option>
                                <option value="583">MICRONESIA - مكرونسيا              </option>
                                <option value="498">MOLDOVA - ملدوفيا               </option>
                                <option value="496">MONGOLIA - منغوليا               </option>
                                <option value="478">MAURITANIA - موريتانا              </option>
                                <option value="480">MAURITIUS - موريشوس               </option>
                                <option value="508">MOZAMBIQUE - موزامبيق              </option>
                                <option value="492">MONACO - موناكو                </option>
                                <option value="500">MONTSERRAT - مونتسرات              </option>
                                <option value="104">MYANMAR - ميانمار               </option>
                                <option value="516">NAMIBIA - ناميبيا               </option>
                                <option value="520">NAURU - نورو                  </option>
                                <option value="524">NEPAL - نيبال                 </option>
                                <option value="566">NIGERIA - نيجيريا               </option>
                                <option value="558">NICARGUA - نيكواراجوا            </option>
                                <option value="570">NIUE - نيو                   </option>
                                <option value="540">NEW CALEDONIA - نيو كاليدونيا         </option>
                                <option value="554">NEW ZEALAND - نيوزيلاندا            </option>
                                <option value="332">HAITI - هايتي                 </option>
                                <option value="528">NETHERLANDS - هولندا                </option>
                                <option value="344">HONG KONG - هونج كونج             </option>
                                <option value="340">HONDURAS - هوندوراس              </option>
                                <option value="990">TRAVEL DOCUMENT - وثيقة سفر             </option>
                                <option value="890">YUGOSLVA - يوغوسلافيا            </option>                    
</select>